#!/usr/bin/env python3
"""
Generate downloadable PDF questionnaires and templates for igawo.pl
"""
import os
from fpdf import FPDF

OUTPUT_DIR = "public/downloads"
os.makedirs(OUTPUT_DIR, exist_ok=True)

class IgawoPDF(FPDF):
    def header(self):
        # Logo placeholder / brand header
        self.set_font("DejaVu", "B", 10)
        self.set_text_color(40, 60, 80)
        self.cell(0, 8, "IGAWO.pl — Izabela Gawłowska-Wolak", ln=True, align="L")
        self.set_draw_color(180, 140, 80)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("DejaVu", "", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Strona {self.page_no()}/{{nb}}  |  igawo14@gmail.com  |  +48 570 016 826  |  +49 157 526 669 22", align="C")

    def section_title(self, title):
        self.set_font("DejaVu", "B", 12)
        self.set_text_color(40, 60, 80)
        self.cell(0, 8, title, ln=True)
        self.set_draw_color(180, 140, 80)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def field_label(self, label):
        self.set_font("DejaVu", "B", 9)
        self.set_text_color(50, 50, 50)
        self.cell(0, 6, label, ln=True)

    def field_line(self, height=8):
        self.set_draw_color(180, 180, 180)
        self.line(10, self.get_y() + height - 2, 200, self.get_y() + height - 2)
        self.ln(height)

    def body_text(self, text):
        self.set_font("DejaVu", "", 9)
        self.set_text_color(60, 60, 60)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def info_box(self, text):
        self.set_fill_color(245, 245, 240)
        self.set_draw_color(180, 140, 80)
        self.set_font("DejaVu", "", 8)
        self.set_text_color(80, 80, 80)
        self.multi_cell(0, 5, text, border=1, fill=True)
        self.ln(3)


def add_dejavu_fonts(pdf):
    # System DejaVu fonts with Unicode support for Polish/German characters
    pdf.add_font("DejaVu", "", "/usr/share/fonts/TTF/DejaVuSans.ttf")
    pdf.add_font("DejaVu", "B", "/usr/share/fonts/TTF/DejaVuSans-Bold.ttf")
    pdf.add_font("DejaVu", "I", "/usr/share/fonts/TTF/DejaVuSans-Oblique.ttf")
    pdf.add_font("DejaVu", "BI", "/usr/share/fonts/TTF/DejaVuSans-BoldOblique.ttf")


def make_german_questionnaire_pl():
    pdf = IgawoPDF()
    add_dejavu_fonts(pdf)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("DejaVu", "B", 16)
    pdf.set_text_color(40, 60, 80)
    pdf.cell(0, 10, "Kwestionariusz do rozliczenia podatkowego z Niemiec", ln=True, align="C")
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, "Wypełnij najdokładniej, jak potrafisz. Nie musisz znać wszystkich odpowiedzi.", ln=True, align="C")
    pdf.ln(5)

    pdf.info_box("ℹ  Im więcej informacji podasz, tym dokładniejsze będzie oszacowanie Twojego zwrotu. Zaznacz \"nie wiem\" tam, gdzie nie jesteś pewien — pomożemy.")

    pdf.section_title("1. Dane osobowe")
    pdf.field_label("Imię i nazwisko:")
    pdf.field_line()
    pdf.field_label("Data urodzenia (DD.MM.RRRR):")
    pdf.field_line()
    pdf.field_label("Adres zameldowania w Polsce:")
    pdf.field_line(12)
    pdf.field_label("Numer Steuer-ID (jeśli masz — 11 cyfr):")
    pdf.field_line()
    pdf.field_label("Stan cywilny w roku podatkowym:")
    pdf.body_text("□ kawaler/panna  □ żonaty/zamężna  □ rozwiedziony/a  □ wdowiec/wdowa")
    pdf.field_label("Czy Twój małżonek mieszkał w Niemczech w tym roku?")
    pdf.body_text("□ Tak  □ Nie  □ Nie wiem")

    pdf.section_title("2. Praca w Niemczech")
    pdf.field_label("Nazwa pracodawcy / pracodawców:")
    pdf.field_line(12)
    pdf.field_label("Okres zatrudnienia (od – do):")
    pdf.field_line()
    pdf.field_label("Adres pracodawcy (miasto wystarczy):")
    pdf.field_line()
    pdf.field_label("Rodzaj umowy:")
    pdf.body_text("□ Umowa o pracę (Arbeitsvertrag)  □ Zlecenie (Werkvertrag)  □ Inna: _______________")
    pdf.field_label("Czy pracowałeś na nocne zmiany, w święta lub w niedziele?")
    pdf.body_text("□ Tak  □ Nie  □ Nie pamiętam")
    pdf.field_label("Czy korzystałeś z dojazdów do pracy (np. 2. Klasse tax)?")
    pdf.body_text("□ Tak  □ Nie  □ Nie wiem")

    pdf.add_page()
    pdf.section_title("3. Dochody i dokumenty")
    pdf.field_label("Czy masz Lohnabrechnungen (paski wypłat) za cały rok?")
    pdf.body_text("□ Tak, wszystkie  □ Brakuje mi niektórych miesięcy  □ Nie mam żadnych")
    pdf.field_label("Jeśli brakuje — które miesiące?")
    pdf.field_line()
    pdf.field_label("Czy otrzymałeś Jaegernachweis / Lohnsteuerbescheinigung?")
    pdf.body_text("□ Tak  □ Nie  □ Nie wiem, co to jest")
    pdf.field_label("Czy pracowałeś u więcej niż jednego pracodawcy w tym roku?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Czy otrzymałeś zasiłek (Arbeitslosengeld, Krankengeld, Urlaubsgeld)?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Jeśli tak — jaką kwotę i od kiedy do kiedy?")
    pdf.field_line(12)

    pdf.section_title("4. Koszty i ulgi")
    pdf.field_label("Czy ponosiłeś koszty dojazdu do pracy?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Odległość do pracy (w km, w jedną stronę):")
    pdf.field_line()
    pdf.field_label("Czy ponosiłeś koszty zakwaterowania w Niemczech?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Jeśli tak — miesięczny czynsz (około):")
    pdf.field_line()
    pdf.field_label("Czy kupowałeś sprzęt/profesjonalne ubrania na potrzeby pracy?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Czy płaciłeś składki zawodowe (np. do związku zawodowego)?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Czy masz dzieci? Jeśli tak — podaj daty urodzenia:")
    pdf.field_line(12)

    pdf.add_page()
    pdf.section_title("5. Dane bankowe do zwrotu")
    pdf.field_label("Imię i nazwisko właściciela konta:")
    pdf.field_line()
    pdf.field_label("Nazwa banku:")
    pdf.field_line()
    pdf.field_label("Numer IBAN:")
    pdf.field_line()
    pdf.field_label("SWIFT/BIC (jeśli konto polskie):")
    pdf.field_line()

    pdf.section_title("6. Historia podatkowa")
    pdf.field_label("Czy rozliczałeś się wcześniej z Niemiec?")
    pdf.body_text("□ Tak  □ Nie  □ To moje pierwsze rozliczenie")
    pdf.field_label("Czy otrzymałeś kiedykolwiek decyzję urzędu skarbowego (Steuerbescheid)?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Czy urząd kiedykolwiek domagał się zwrotu pieniędzy?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Czy masz zaległe rozliczenia z poprzednich lat?")
    pdf.body_text("□ Tak, lata: __________  □ Nie")

    pdf.section_title("7. Dodatkowe informacje")
    pdf.field_label("Czy jest coś, o czym powinniśmy wiedzieć? (np. zmiana pracy, przeprowadzka, choroba)")
    pdf.field_line(24)

    pdf.info_box("E-mail:  Wyślij wypełniony kwestionariusz na igawo14@gmail.com lub prześlij zdjęcia przez WhatsApp/SMS na +48 570 016 826. Skontaktujemy się z Tobą w ciągu 24h z wstępnym oszacowaniem.")

    pdf.output(f"{OUTPUT_DIR}/kwestionariusz-niemcy.pdf")
    print("Generated: kwestionariusz-niemcy.pdf")


def make_german_questionnaire_en():
    pdf = IgawoPDF()
    add_dejavu_fonts(pdf)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("DejaVu", "B", 16)
    pdf.set_text_color(40, 60, 80)
    pdf.cell(0, 10, "Tax Return Questionnaire — Germany", ln=True, align="C")
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, "Fill in as accurately as you can. You do not need to know every answer.", ln=True, align="C")
    pdf.ln(5)

    pdf.info_box("ℹ  The more details you provide, the more accurate your refund estimate will be. Mark \"not sure\" where unsure — we will help.")

    pdf.section_title("1. Personal Details")
    pdf.field_label("Full name:")
    pdf.field_line()
    pdf.field_label("Date of birth (DD.MM.YYYY):")
    pdf.field_line()
    pdf.field_label("Registered address in Poland:")
    pdf.field_line(12)
    pdf.field_label("Steuer-ID number (if you have one — 11 digits):")
    pdf.field_line()
    pdf.field_label("Marital status during the tax year:")
    pdf.body_text("□ Single  □ Married  □ Divorced  □ Widowed")
    pdf.field_label("Did your spouse live in Germany that year?")
    pdf.body_text("□ Yes  □ No  □ Not sure")

    pdf.section_title("2. Employment in Germany")
    pdf.field_label("Employer name(s):")
    pdf.field_line(12)
    pdf.field_label("Employment period (from – to):")
    pdf.field_line()
    pdf.field_label("Employer city:")
    pdf.field_line()
    pdf.field_label("Type of contract:")
    pdf.body_text("□ Employment contract  □ Service contract  □ Other: _______________")
    pdf.field_label("Did you work night shifts, holidays or Sundays?")
    pdf.body_text("□ Yes  □ No  □ Can't remember")
    pdf.field_label("Did you commute to work?")
    pdf.body_text("□ Yes  □ No  □ Not sure")

    pdf.add_page()
    pdf.section_title("3. Income & Documents")
    pdf.field_label("Do you have Lohnabrechnungen (pay slips) for the whole year?")
    pdf.body_text("□ Yes, all  □ Missing some months  □ None")
    pdf.field_label("If missing — which months?")
    pdf.field_line()
    pdf.field_label("Did you receive Jaegernachweis / Lohnsteuerbescheinigung?")
    pdf.body_text("□ Yes  □ No  □ Not sure what that is")
    pdf.field_label("Did you work for more than one employer that year?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("Did you receive any benefits (Arbeitslosengeld, Krankengeld, Urlaubsgeld)?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("If yes — amount and period:")
    pdf.field_line(12)

    pdf.section_title("4. Expenses & Deductions")
    pdf.field_label("Did you have commuting costs?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("Distance to work (one way, in km):")
    pdf.field_line()
    pdf.field_label("Did you pay for accommodation in Germany?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("If yes — monthly rent (approximate):")
    pdf.field_line()
    pdf.field_label("Did you buy work equipment or professional clothing?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("Did you pay professional membership fees (e.g. union)?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("Do you have children? If yes — birth dates:")
    pdf.field_line(12)

    pdf.add_page()
    pdf.section_title("5. Bank Details for Refund")
    pdf.field_label("Account holder name:")
    pdf.field_line()
    pdf.field_label("Bank name:")
    pdf.field_line()
    pdf.field_label("IBAN:")
    pdf.field_line()
    pdf.field_label("SWIFT/BIC (if Polish account):")
    pdf.field_line()

    pdf.section_title("6. Tax History")
    pdf.field_label("Have you filed a German tax return before?")
    pdf.body_text("□ Yes  □ No  □ This is my first time")
    pdf.field_label("Have you ever received a Steuerbescheid (tax decision)?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("Has the tax office ever demanded money back?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("Do you have any pending returns from previous years?")
    pdf.body_text("□ Yes, years: __________  □ No")

    pdf.section_title("7. Additional Information")
    pdf.field_label("Is there anything else we should know? (job change, move, illness)")
    pdf.field_line(24)

    pdf.info_box("E-mail:  Send the completed questionnaire to igawo14@gmail.com or share photos via WhatsApp/SMS to +48 570 016 826. We will contact you within 24 hours with a preliminary estimate.")

    pdf.output(f"{OUTPUT_DIR}/questionnaire-germany.pdf")
    print("Generated: questionnaire-germany.pdf")


def make_german_questionnaire_de():
    pdf = IgawoPDF()
    add_dejavu_fonts(pdf)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("DejaVu", "B", 16)
    pdf.set_text_color(40, 60, 80)
    pdf.cell(0, 10, "Steuererklärungs-Fragebogen — Deutschland", ln=True, align="C")
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, "Füllen Sie ihn so genau wie möglich aus. Sie müssen nicht alle Antworten kennen.", ln=True, align="C")
    pdf.ln(5)

    pdf.info_box("ℹ  Je mehr Angaben Sie machen, desto genauer wird Ihre Erstattungsschätzung. Markieren Sie \"unsicher\", wo Sie nicht sicher sind — wir helfen Ihnen.")

    pdf.section_title("1. Persönliche Daten")
    pdf.field_label("Vor- und Nachname:")
    pdf.field_line()
    pdf.field_label("Geburtsdatum (TT.MM.JJJJ):")
    pdf.field_line()
    pdf.field_label("Meldeadresse in Polen:")
    pdf.field_line(12)
    pdf.field_label("Steuer-ID-Nummer (falls vorhanden — 11 Ziffern):")
    pdf.field_line()
    pdf.field_label("Familienstand im Steuerjahr:")
    pdf.body_text("□ Ledig  □ Verheiratet  □ Geschieden  □ Verwitwet")
    pdf.field_label("Hat Ihr Ehepartner im Steuerjahr in Deutschland gelebt?")
    pdf.body_text("□ Ja  □ Nein  □ Unsicher")

    pdf.section_title("2. Beschäftigung in Deutschland")
    pdf.field_label("Name des Arbeitgebers / der Arbeitgeber:")
    pdf.field_line(12)
    pdf.field_label("Beschäftigungszeitraum (von – bis):")
    pdf.field_line()
    pdf.field_label("Ort des Arbeitgebers:")
    pdf.field_line()
    pdf.field_label("Art des Vertrags:")
    pdf.body_text("□ Arbeitsvertrag  □ Werkvertrag  □ Sonstiges: _______________")
    pdf.field_label("Haben Sie Nachtschicht, Feiertage oder Sonntage gearbeitet?")
    pdf.body_text("□ Ja  □ Nein  □ Weiß ich nicht mehr")
    pdf.field_label("Haben Sie Fahrkosten zur Arbeit gehabt?")
    pdf.body_text("□ Ja  □ Nein  □ Unsicher")

    pdf.add_page()
    pdf.section_title("3. Einkommen & Unterlagen")
    pdf.field_label("Haben Sie Lohnabrechnungen für das ganze Jahr?")
    pdf.body_text("□ Ja, alle  □ Einige Monate fehlen  □ Keine")
    pdf.field_label("Falls nicht — welche Monate fehlen?")
    pdf.field_line()
    pdf.field_label("Haben Sie Jaegernachweis / Lohnsteuerbescheinigung erhalten?")
    pdf.body_text("□ Ja  □ Nein  □ Weiß ich nicht, was das ist")
    pdf.field_label("Haben Sie bei mehr als einem Arbeitgeber gearbeitet?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Haben Sie Leistungen erhalten (Arbeitslosengeld, Krankengeld, Urlaubsgeld)?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Falls ja — Betrag und Zeitraum:")
    pdf.field_line(12)

    pdf.section_title("4. Kosten & Abzüge")
    pdf.field_label("Hatten Sie Fahrkosten zur Arbeit?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Entfernung zur Arbeit (einfach, in km):")
    pdf.field_line()
    pdf.field_label("Hatten Sie Wohnkosten in Deutschland?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Falls ja — monatliche Miete (ca.):")
    pdf.field_line()
    pdf.field_label("Haben Sie Arbeitsmittel oder Berufskleidung gekauft?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Haben Sie Berufsbeiträge gezahlt (z. B. Gewerkschaft)?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Haben Sie Kinder? Falls ja — Geburtsdaten:")
    pdf.field_line(12)

    pdf.add_page()
    pdf.section_title("5. Bankdaten für die Erstattung")
    pdf.field_label("Kontoinhaber:")
    pdf.field_line()
    pdf.field_label("Bankname:")
    pdf.field_line()
    pdf.field_label("IBAN:")
    pdf.field_line()
    pdf.field_label("SWIFT/BIC (bei polnischem Konto):")
    pdf.field_line()

    pdf.section_title("6. Steuerliche Vorgeschichte")
    pdf.field_label("Haben Sie schon einmal eine deutsche Steuererklärung abgegeben?")
    pdf.body_text("□ Ja  □ Nein  □ Das ist mein erstes Mal")
    pdf.field_label("Haben Sie jemals einen Steuerbescheid erhalten?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Hat das Finanzamt jemals Geld zurückverlangt?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Haben Sie offene Erklärungen aus Vorjahren?")
    pdf.body_text("□ Ja, Jahre: __________  □ Nein")

    pdf.section_title("7. Zusätzliche Informationen")
    pdf.field_label("Gibt es noch etwas, das wir wissen sollten? (Arbeitsplatzwechsel, Umzug, Krankheit)")
    pdf.field_line(24)

    pdf.info_box("E-mail:  Senden Sie den ausgefüllten Fragebogen an igawo14@gmail.com oder teilen Sie Fotos per WhatsApp/SMS an +48 570 016 826. Wir melden uns innerhalb von 24 Stunden mit einer ersten Schätzung.")

    pdf.output(f"{OUTPUT_DIR}/fragebogen-deutschland.pdf")
    print("Generated: fragebogen-deutschland.pdf")


def make_dutch_questionnaire_pl():
    pdf = IgawoPDF()
    add_dejavu_fonts(pdf)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("DejaVu", "B", 16)
    pdf.set_text_color(40, 60, 80)
    pdf.cell(0, 10, "Kwestionariusz do rozliczenia podatkowego z Holandii", ln=True, align="C")
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, "Wypełnij najdokładniej, jak potrafisz. Nie musisz znać wszystkich odpowiedzi.", ln=True, align="C")
    pdf.ln(5)

    pdf.info_box("ℹ  Im więcej informacji podasz, tym dokładniejsze będzie oszacowanie Twojego zwrotu. Zaznacz \"nie wiem\" tam, gdzie nie jesteś pewien — pomożemy.")

    pdf.section_title("1. Dane osobowe")
    pdf.field_label("Imię i nazwisko:")
    pdf.field_line()
    pdf.field_label("Data urodzenia (DD.MM.RRRR):")
    pdf.field_line()
    pdf.field_label("Adres zameldowania w Polsce:")
    pdf.field_line(12)
    pdf.field_label("Numer BSN (burgerservicenummer, jeśli masz):")
    pdf.field_line()
    pdf.field_label("Stan cywilny w roku podatkowym:")
    pdf.body_text("□ kawaler/panna  □ żonaty/zamężna  □ rozwiedziony/a  □ wdowiec/wdowa")

    pdf.section_title("2. Praca w Holandii")
    pdf.field_label("Nazwa pracodawcy / pracodawców (użyjholenderskiej nazwy):")
    pdf.field_line(12)
    pdf.field_label("Okres zatrudnienia (od – do):")
    pdf.field_line()
    pdf.field_label("Miasto, w którym pracowałeś:")
    pdf.field_line()
    pdf.field_label("Rodzaj umowy:")
    pdf.body_text("□ Umowa o pracę (vast contract)  □ Tymczasowa (uitzendovereenkomst)  □ Inna: _______________")
    pdf.field_label("Czy korzystałeś z ulgi 30% ruling?")
    pdf.body_text("□ Tak  □ Nie  □ Nie wiem, co to jest")
    pdf.field_label("Czy pracowałeś przez pośrednika (agencja zatrudnienia)?")
    pdf.body_text("□ Tak  □ Nie")

    pdf.add_page()
    pdf.section_title("3. Dochody i dokumenty")
    pdf.field_label("Czy masz roczne zestawienie (jaaropgave) od pracodawcy?")
    pdf.body_text("□ Tak  □ Nie  □ Nie wiem, co to jest")
    pdf.field_label("Czy pracowałeś u więcej niż jednego pracodawcy w tym roku?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Czy otrzymywałeś zasiłek (WW, ZW, WIA)?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Jeśli tak — jaką kwotę i od kiedy do kiedy?")
    pdf.field_line(12)
    pdf.field_label("Czy pracowałeś na nocne zmiany, w święta lub w niedziele?")
    pdf.body_text("□ Tak  □ Nie  □ Nie pamiętam")

    pdf.section_title("4. Koszty i ulgi")
    pdf.field_label("Czy ponosiłeś koszty dojazdu do pracy (prywatny samochód lub transport publiczny)?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Odległość do pracy (w km, w jedną stronę):")
    pdf.field_line()
    pdf.field_label("Czy ponosiłeś koszty zakwaterowania w Holandii?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Jeśli tak — miesięczny czynsz (około):")
    pdf.field_line()
    pdf.field_label("Czy kupowałeś sprzęt/profesjonalne ubrania na potrzeby pracy?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Czy płaciłeś za ubezpieczenie zdrowotne w Holandii (zorgverzekering)?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Czy masz dzieci? Jeśli tak — podaj daty urodzenia:")
    pdf.field_line(12)

    pdf.add_page()
    pdf.section_title("5. Dane bankowe do zwrotu")
    pdf.field_label("Imię i nazwisko właściciela konta:")
    pdf.field_line()
    pdf.field_label("Nazwa banku:")
    pdf.field_line()
    pdf.field_label("Numer IBAN:")
    pdf.field_line()
    pdf.field_label("SWIFT/BIC (jeśli konto polskie):")
    pdf.field_line()

    pdf.section_title("6. Historia podatkowa")
    pdf.field_label("Czy rozliczałeś się wcześniej z Holandii?")
    pdf.body_text("□ Tak  □ Nie  □ To moje pierwsze rozliczenie")
    pdf.field_label("Czy otrzymałeś kiedykolwiek decyzję urzędu skarbowego (aanslag)?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Czy urząd kiedykolwiek domagał się zwrotu pieniędzy?")
    pdf.body_text("□ Tak  □ Nie")
    pdf.field_label("Czy masz zaległe rozliczenia z poprzednich lat?")
    pdf.body_text("□ Tak, lata: __________  □ Nie")

    pdf.section_title("7. Dodatkowe informacje")
    pdf.field_label("Czy jest coś, o czym powinniśmy wiedzieć? (np. zmiana pracy, przeprowadzka, choroba)")
    pdf.field_line(24)

    pdf.info_box("E-mail:  Wyślij wypełniony kwestionariusz na igawo14@gmail.com lub prześlij zdjęcia przez WhatsApp/SMS na +48 570 016 826. Skontaktujemy się z Tobą w ciągu 24h z wstępnym oszacowaniem.")

    pdf.output(f"{OUTPUT_DIR}/kwestionariusz-holandia.pdf")
    print("Generated: kwestionariusz-holandia.pdf")


def make_dutch_questionnaire_en():
    pdf = IgawoPDF()
    add_dejavu_fonts(pdf)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("DejaVu", "B", 16)
    pdf.set_text_color(40, 60, 80)
    pdf.cell(0, 10, "Tax Return Questionnaire — Netherlands", ln=True, align="C")
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, "Fill in as accurately as you can. You do not need to know every answer.", ln=True, align="C")
    pdf.ln(5)

    pdf.info_box("ℹ  The more details you provide, the more accurate your refund estimate will be. Mark \"not sure\" where unsure — we will help.")

    pdf.section_title("1. Personal Details")
    pdf.field_label("Full name:")
    pdf.field_line()
    pdf.field_label("Date of birth (DD.MM.YYYY):")
    pdf.field_line()
    pdf.field_label("Registered address in Poland:")
    pdf.field_line(12)
    pdf.field_label("BSN number (burgerservicenummer, if you have one):")
    pdf.field_line()
    pdf.field_label("Marital status during the tax year:")
    pdf.body_text("□ Single  □ Married  □ Divorced  □ Widowed")

    pdf.section_title("2. Employment in the Netherlands")
    pdf.field_label("Employer name(s) (Dutch name if possible):")
    pdf.field_line(12)
    pdf.field_label("Employment period (from – to):")
    pdf.field_line()
    pdf.field_label("City where you worked:")
    pdf.field_line()
    pdf.field_label("Type of contract:")
    pdf.body_text("□ Permanent contract  □ Temporary (uitzendovereenkomst)  □ Other: _______________")
    pdf.field_label("Did you use the 30% ruling?")
    pdf.body_text("□ Yes  □ No  □ Not sure what that is")
    pdf.field_label("Did you work through an employment agency?")
    pdf.body_text("□ Yes  □ No")

    pdf.add_page()
    pdf.section_title("3. Income & Documents")
    pdf.field_label("Do you have the annual statement (jaaropgave) from your employer?")
    pdf.body_text("□ Yes  □ No  □ Not sure what that is")
    pdf.field_label("Did you work for more than one employer that year?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("Did you receive any benefits (WW, ZW, WIA)?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("If yes — amount and period:")
    pdf.field_line(12)
    pdf.field_label("Did you work night shifts, holidays or Sundays?")
    pdf.body_text("□ Yes  □ No  □ Can't remember")

    pdf.section_title("4. Expenses & Deductions")
    pdf.field_label("Did you have commuting costs (private car or public transport)?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("Distance to work (one way, in km):")
    pdf.field_line()
    pdf.field_label("Did you pay for accommodation in the Netherlands?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("If yes — monthly rent (approximate):")
    pdf.field_line()
    pdf.field_label("Did you buy work equipment or professional clothing?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("Did you pay for Dutch health insurance (zorgverzekering)?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("Do you have children? If yes — birth dates:")
    pdf.field_line(12)

    pdf.add_page()
    pdf.section_title("5. Bank Details for Refund")
    pdf.field_label("Account holder name:")
    pdf.field_line()
    pdf.field_label("Bank name:")
    pdf.field_line()
    pdf.field_label("IBAN:")
    pdf.field_line()
    pdf.field_label("SWIFT/BIC (if Polish account):")
    pdf.field_line()

    pdf.section_title("6. Tax History")
    pdf.field_label("Have you filed a Dutch tax return before?")
    pdf.body_text("□ Yes  □ No  □ This is my first time")
    pdf.field_label("Have you ever received a tax assessment (aanslag)?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("Has the tax office ever demanded money back?")
    pdf.body_text("□ Yes  □ No")
    pdf.field_label("Do you have any pending returns from previous years?")
    pdf.body_text("□ Yes, years: __________  □ No")

    pdf.section_title("7. Additional Information")
    pdf.field_label("Is there anything else we should know? (job change, move, illness)")
    pdf.field_line(24)

    pdf.info_box("E-mail:  Send the completed questionnaire to igawo14@gmail.com or share photos via WhatsApp/SMS to +48 570 016 826. We will contact you within 24 hours with a preliminary estimate.")

    pdf.output(f"{OUTPUT_DIR}/questionnaire-netherlands.pdf")
    print("Generated: questionnaire-netherlands.pdf")


def make_dutch_questionnaire_de():
    pdf = IgawoPDF()
    add_dejavu_fonts(pdf)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("DejaVu", "B", 16)
    pdf.set_text_color(40, 60, 80)
    pdf.cell(0, 10, "Steuererklärungs-Fragebogen — Niederlande", ln=True, align="C")
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, "Füllen Sie ihn so genau wie möglich aus. Sie müssen nicht alle Antworten kennen.", ln=True, align="C")
    pdf.ln(5)

    pdf.info_box("ℹ  Je mehr Angaben Sie machen, desto genauer wird Ihre Erstattungsschätzung. Markieren Sie \"unsicher\", wo Sie nicht sicher sind — wir helfen Ihnen.")

    pdf.section_title("1. Persönliche Daten")
    pdf.field_label("Vor- und Nachname:")
    pdf.field_line()
    pdf.field_label("Geburtsdatum (TT.MM.JJJJ):")
    pdf.field_line()
    pdf.field_label("Meldeadresse in Polen:")
    pdf.field_line(12)
    pdf.field_label("BSN-Nummer (burgerservicenummer, falls vorhanden):")
    pdf.field_line()
    pdf.field_label("Familienstand im Steuerjahr:")
    pdf.body_text("□ Ledig  □ Verheiratet  □ Geschieden  □ Verwitwet")

    pdf.section_title("2. Beschäftigung in den Niederlanden")
    pdf.field_label("Name des Arbeitgebers / der Arbeitgeber (niederländischer Name):")
    pdf.field_line(12)
    pdf.field_label("Beschäftigungszeitraum (von – bis):")
    pdf.field_line()
    pdf.field_label("Stadt, in der Sie gearbeitet haben:")
    pdf.field_line()
    pdf.field_label("Art des Vertrags:")
    pdf.body_text("□ Unbefristeter Vertrag  □ Zeitarbeit (uitzendovereenkomst)  □ Sonstiges: _______________")
    pdf.field_label("Haben Sie die 30%-Ruling genutzt?")
    pdf.body_text("□ Ja  □ Nein  □ Weiß ich nicht, was das ist")
    pdf.field_label("Haben Sie über eine Zeitarbeitsfirma gearbeitet?")
    pdf.body_text("□ Ja  □ Nein")

    pdf.add_page()
    pdf.section_title("3. Einkommen & Unterlagen")
    pdf.field_label("Haben Sie die Jahresaufstellung (jaaropgave) vom Arbeitgeber?")
    pdf.body_text("□ Ja  □ Nein  □ Weiß ich nicht, was das ist")
    pdf.field_label("Haben Sie bei mehr als einem Arbeitgeber gearbeitet?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Haben Sie Leistungen erhalten (WW, ZW, WIA)?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Falls ja — Betrag und Zeitraum:")
    pdf.field_line(12)
    pdf.field_label("Haben Sie Nachtschicht, Feiertage oder Sonntage gearbeitet?")
    pdf.body_text("□ Ja  □ Nein  □ Weiß ich nicht mehr")

    pdf.section_title("4. Kosten & Abzüge")
    pdf.field_label("Hatten Sie Fahrkosten zur Arbeit (Privatwagen oder ÖPNV)?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Entfernung zur Arbeit (einfach, in km):")
    pdf.field_line()
    pdf.field_label("Hatten Sie Wohnkosten in den Niederlanden?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Falls ja — monatliche Miete (ca.):")
    pdf.field_line()
    pdf.field_label("Haben Sie Arbeitsmittel oder Berufskleidung gekauft?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Haben Sie die niederländische Krankenversicherung (zorgverzekering) bezahlt?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Haben Sie Kinder? Falls ja — Geburtsdaten:")
    pdf.field_line(12)

    pdf.add_page()
    pdf.section_title("5. Bankdaten für die Erstattung")
    pdf.field_label("Kontoinhaber:")
    pdf.field_line()
    pdf.field_label("Bankname:")
    pdf.field_line()
    pdf.field_label("IBAN:")
    pdf.field_line()
    pdf.field_label("SWIFT/BIC (bei polnischem Konto):")
    pdf.field_line()

    pdf.section_title("6. Steuerliche Vorgeschichte")
    pdf.field_label("Haben Sie schon einmal eine niederländische Steuererklärung abgegeben?")
    pdf.body_text("□ Ja  □ Nein  □ Das ist mein erstes Mal")
    pdf.field_label("Haben Sie jemals einen Steuerbescheid (aanslag) erhalten?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Hat das Finanzamt jemals Geld zurückverlangt?")
    pdf.body_text("□ Ja  □ Nein")
    pdf.field_label("Haben Sie offene Erklärungen aus Vorjahren?")
    pdf.body_text("□ Ja, Jahre: __________  □ Nein")

    pdf.section_title("7. Zusätzliche Informationen")
    pdf.field_label("Gibt es noch etwas, das wir wissen sollten? (Arbeitsplatzwechsel, Umzug, Krankheit)")
    pdf.field_line(24)

    pdf.info_box("E-mail:  Senden Sie den ausgefüllten Fragebogen an igawo14@gmail.com oder teilen Sie Fotos per WhatsApp/SMS an +48 570 016 826. Wir melden uns innerhalb von 24 Stunden mit einer ersten Schätzung.")

    pdf.output(f"{OUTPUT_DIR}/fragebogen-niederlande.pdf")
    print("Generated: fragebogen-niederlande.pdf")


def make_kindergeld_template_pl():
    pdf = IgawoPDF()
    add_dejavu_fonts(pdf)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("DejaVu", "B", 16)
    pdf.set_text_color(40, 60, 80)
    pdf.cell(0, 10, "Wzór wypełnionego wniosku Kindergeld (KG 1–6)", ln=True, align="C")
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, "Przykład poprawnie uzupełnionych formularzy — na podstawie fikcyjnych danych", ln=True, align="C")
    pdf.ln(5)

    pdf.info_box("⚠  To tylko przykład. Każda sytuacja jest inna. Skonsultuj swój wniosek przed wysłaniem. Wypełniony wniosek należy wysłać do Familienkasse odpowiedniej dla miejsca pracy.")

    pdf.section_title("Formularz KG 1 — Wniosek o Kindergeld")
    pdf.body_text("Poniżej znajduje się przykład wypełnienia najważniejszych pól formularza KG 1.")

    pdf.field_label("Familienkasse (urząd rodzinny przypisany do pracodawcy):")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Familienkasse der Bundesagentur für Arbeit — Düsseldorf", ln=True)
    pdf.field_label("Imię i nazwisko wnioskodawcy:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Anna Kowalska", ln=True)
    pdf.field_label("Adres zameldowania w Polsce:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "ul. Leśna 12, 00-001 Warszawa, Polska", ln=True)
    pdf.field_label("Numer Steuer-ID wnioskodawcy:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "12 345 678 901", ln=True)
    pdf.field_label("Numer kontaktowy:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "+48 500 123 456", ln=True)

    pdf.section_title("Formularz KG 2 — Dane dziecka / dzieci")
    pdf.body_text("Wypełnij osobno dla każdego dziecka.")
    pdf.field_label("Imię i nazwisko dziecka:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Piotr Kowalski", ln=True)
    pdf.field_label("Data urodzenia:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "15.03.2018", ln=True)
    pdf.field_label("Miejsce urodzenia:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Warszawa, Polska", ln=True)
    pdf.field_label("Numer ubezpieczeniowy dziecka (jeśli ma niemiecki):")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "brak — dziecko zameldowane w Polsce", ln=True)
    pdf.field_label("Czy dziecko mieszka razem z wnioskodawcą?")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Tak — stałe miejsce zamieszkania u rodzica w Polsce", ln=True)

    pdf.add_page()
    pdf.section_title("Formularz KG 3 — Dane drugiego rodzica (drugiego opiekuna)")
    pdf.body_text("Wypełnij, jeśli drugi rodzic żyje i nie mieszka z wnioskodawcą.")
    pdf.field_label("Imię i nazwisko drugiego rodzica:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Jan Kowalski", ln=True)
    pdf.field_label("Adres zameldowania drugiego rodzica:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "ul. Leśna 12, 00-001 Warszawa, Polska (wspólne zameldowanie)", ln=True)
    pdf.field_label("Czy drugi rodzic pracuje w Niemczech?")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Nie — pracuje w Polsce", ln=True)
    pdf.field_label("Czy drugi rodzic pobiera Kindergeld z innego tytułu?")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Nie", ln=True)

    pdf.section_title("Formularz KG 4 — Oświadczenie o sytuacji mieszkaniowej")
    pdf.body_text("Potwierdzenie, że dziecko mieszka z wnioskodawcą.")
    pdf.field_label("Adres, pod którym faktycznie mieszka dziecko:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "ul. Leśna 12, 00-001 Warszawa, Polska", ln=True)
    pdf.field_label("Data rozpoczęcia wspólnego zamieszkania:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "od urodzenia dziecka — 15.03.2018", ln=True)

    pdf.section_title("Formularz KG 5 — Zgoda drugiego rodzica (jeśli wymagana)")
    pdf.body_text("Jeśli rodzice są w separacji lub drugi rodzic pracuje za granicą — wymagana jest zgoda na przekazanie Kindergeld do wnioskodawcy.")
    pdf.field_label("Podpis drugiego rodzica + data:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Jan Kowalski, 05.01.2025", ln=True)
    pdf.field_label("Czy zgoda jest poświadczona notarialnie lub urzędowo?")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Nie wymagana — rodzice wspólnie zameldowani", ln=True)

    pdf.section_title("Formularz KG 6 — Dane pracodawcy i ubezpieczeniowe")
    pdf.field_label("Nazwa pracodawcy w Niemczech:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Muster GmbH, Kolonia", ln=True)
    pdf.field_label("Numer ubezpieczeniowy (Sozialversicherungsnummer) wnioskodawcy:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "12 123456 A 123", ln=True)
    pdf.field_label("Data rozpoczęcia pracy w Niemczech:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "01.03.2022 — obecnie", ln=True)

    pdf.add_page()
    pdf.section_title("Najczęstsze błędy przy wypełnianiu")
    pdf.body_text("1. Nieprawidłowy adres Familienkasse — zawsze sprawdź, który urząd jest przypisany do Twojego pracodawcy.")
    pdf.body_text("2. Brak numeru Steuer-ID — jeśli go nie masz, zaznacz odpowiednie pole i dołącz kopię paszportu.")
    pdf.body_text("3. Niekompletne dane dziecka — podaj dokładną datę urodzenia i miejsce z aktu urodzenia.")
    pdf.body_text("4. Brak podpisu drugiego rodzica — jeśli rodzice są w separacji, zgoda jest obligatoryjna.")
    pdf.body_text("5. Nieaktualny adres — jeśli się przeprowadziłeś, zgłoś zmianę najpierw w urzędzie meldunkowym.")
    pdf.body_text("6. Wysyłanie oryginałów — zawsze wysyłaj kopie, zachowaj oryginały dla siebie.")

    pdf.section_title("Wymagane załączniki (kserokopie)")
    pdf.body_text("□ Akt urodzenia dziecka (z tłumaczeniem przysięgłym na język niemiecki)")
    pdf.body_text("□ Paszport lub dowód osobisty wnioskodawcy")
    pdf.body_text("□ Lohnabrechnung / Lohnsteuerbescheinigung (potwierdzenie zatrudnienia w Niemczech)")
    pdf.body_text("□ Meldung (potwierdzenie zameldowania dziecka w Polsce — z urzędu miasta)")
    pdf.body_text("□ Zgoda drugiego rodzica (jeśli wymagana)")

    pdf.info_box("E-mail:  Masz wątpliwości? Wyślij swoje wypełnione formularze na igawo14@gmail.com lub zadzwoń +48 570 016 826. Sprawdzimy, czy wszystko jest poprawnie wypełnione, zanim wyślesz wniosek do Familienkasse.")

    pdf.output(f"{OUTPUT_DIR}/wniosek-kindergeld.pdf")
    print("Generated: wniosek-kindergeld.pdf")


def make_kindergeld_template_en():
    pdf = IgawoPDF()
    add_dejavu_fonts(pdf)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("DejaVu", "B", 16)
    pdf.set_text_color(40, 60, 80)
    pdf.cell(0, 10, "Kindergeld Application Template (KG 1–6)", ln=True, align="C")
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, "Example of correctly completed forms — based on fictional data", ln=True, align="C")
    pdf.ln(5)

    pdf.info_box("⚠  This is only an example. Every situation is different. Consult us before submitting. The completed application must be sent to the Familienkasse assigned to your employer.")

    pdf.section_title("Form KG 1 — Kindergeld Application")
    pdf.body_text("Below is an example of how to fill in the most important fields of form KG 1.")

    pdf.field_label("Familienkasse (family benefits office assigned to employer):")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Familienkasse der Bundesagentur für Arbeit — Düsseldorf", ln=True)
    pdf.field_label("Applicant's full name:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Anna Kowalska", ln=True)
    pdf.field_label("Registered address in Poland:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "ul. Leśna 12, 00-001 Warszawa, Polska", ln=True)
    pdf.field_label("Applicant's Steuer-ID:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "12 345 678 901", ln=True)
    pdf.field_label("Contact phone number:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "+48 500 123 456", ln=True)

    pdf.section_title("Form KG 2 — Child's Details")
    pdf.body_text("Fill separately for each child.")
    pdf.field_label("Child's full name:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Piotr Kowalski", ln=True)
    pdf.field_label("Date of birth:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "15.03.2018", ln=True)
    pdf.field_label("Place of birth:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Warszawa, Polska", ln=True)
    pdf.field_label("Child's social security number (if German):")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "none — child registered in Poland", ln=True)
    pdf.field_label("Does the child live with the applicant?")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Yes — permanent residence with parent in Poland", ln=True)

    pdf.add_page()
    pdf.section_title("Form KG 3 — Second Parent / Guardian Details")
    pdf.body_text("Fill in if the second parent is alive and does not live with the applicant.")
    pdf.field_label("Second parent's full name:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Jan Kowalski", ln=True)
    pdf.field_label("Second parent's registered address:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "ul. Leśna 12, 00-001 Warszawa, Polska (joint registration)", ln=True)
    pdf.field_label("Does the second parent work in Germany?")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "No — works in Poland", ln=True)
    pdf.field_label("Does the second parent receive Kindergeld from another source?")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "No", ln=True)

    pdf.section_title("Form KG 4 — Housing Situation Declaration")
    pdf.body_text("Confirmation that the child lives with the applicant.")
    pdf.field_label("Address where the child actually lives:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "ul. Leśna 12, 00-001 Warszawa, Polska", ln=True)
    pdf.field_label("Date when cohabitation started:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "since the child's birth — 15.03.2018", ln=True)

    pdf.section_title("Form KG 5 — Second Parent's Consent (if required)")
    pdf.body_text("If parents are separated or the second parent works abroad, consent is required to transfer Kindergeld to the applicant.")
    pdf.field_label("Second parent's signature + date:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Jan Kowalski, 05.01.2025", ln=True)
    pdf.field_label("Is the consent notarised or officially certified?")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Not required — parents jointly registered", ln=True)

    pdf.section_title("Form KG 6 — Employer & Insurance Details")
    pdf.field_label("German employer's name:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Muster GmbH, Cologne", ln=True)
    pdf.field_label("Applicant's social security number (Sozialversicherungsnummer):")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "12 123456 A 123", ln=True)
    pdf.field_label("Employment start date in Germany:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "01.03.2022 — present", ln=True)

    pdf.add_page()
    pdf.section_title("Most Common Mistakes")
    pdf.body_text("1. Wrong Familienkasse address — always check which office is assigned to your employer.")
    pdf.body_text("2. Missing Steuer-ID — if you don't have one, tick the appropriate box and attach a copy of your passport.")
    pdf.body_text("3. Incomplete child details — provide the exact date and place of birth from the birth certificate.")
    pdf.body_text("4. Missing second parent's signature — if parents are separated, consent is mandatory.")
    pdf.body_text("5. Outdated address — if you moved, report the change to the registration office first.")
    pdf.body_text("6. Sending originals — always send copies, keep originals for yourself.")

    pdf.section_title("Required Attachments (copies)")
    pdf.body_text("□ Child's birth certificate (with sworn translation into German)")
    pdf.body_text("□ Applicant's passport or ID card")
    pdf.body_text("□ Lohnabrechnung / Lohnsteuerbescheinigung (proof of employment in Germany)")
    pdf.body_text("□ Meldung (proof of child's registration in Poland — from city hall)")
    pdf.body_text("□ Second parent's consent (if required)")

    pdf.info_box("E-mail:  Have doubts? Send your completed forms to igawo14@gmail.com or call +48 570 016 826. We will check if everything is filled in correctly before you send the application to Familienkasse.")

    pdf.output(f"{OUTPUT_DIR}/kindergeld-application-template.pdf")
    print("Generated: kindergeld-application-template.pdf")


def make_kindergeld_template_de():
    pdf = IgawoPDF()
    add_dejavu_fonts(pdf)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("DejaVu", "B", 16)
    pdf.set_text_color(40, 60, 80)
    pdf.cell(0, 10, "Kindergeld-Antrag-Vorlage (KG 1–6)", ln=True, align="C")
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, "Beispiel korrekt ausgefüllter Formulare — basierend auf fiktiven Daten", ln=True, align="C")
    pdf.ln(5)

    pdf.info_box("⚠  Dies ist nur ein Beispiel. Jede Situation ist anders. Konsultieren Sie uns vor der Einreichung. Der ausgefüllte Antrag muss an die für Ihren Arbeitgeber zuständige Familienkasse gesendet werden.")

    pdf.section_title("Formular KG 1 — Kindergeld-Antrag")
    pdf.body_text("Nachfolgend ein Beispiel für die wichtigsten Felder des Formulars KG 1.")

    pdf.field_label("Familienkasse (dem Arbeitgeber zugeordnetes Familienkassen-Büro):")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Familienkasse der Bundesagentur für Arbeit — Düsseldorf", ln=True)
    pdf.field_label("Vor- und Nachname des Antragstellers:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Anna Kowalska", ln=True)
    pdf.field_label("Meldeadresse in Polen:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "ul. Leśna 12, 00-001 Warszawa, Polska", ln=True)
    pdf.field_label("Steuer-ID-Nummer des Antragstellers:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "12 345 678 901", ln=True)
    pdf.field_label("Kontakt-Telefonnummer:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "+48 500 123 456", ln=True)

    pdf.section_title("Formular KG 2 — Angaben zum Kind")
    pdf.body_text("Für jedes Kind separat ausfüllen.")
    pdf.field_label("Vor- und Nachname des Kindes:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Piotr Kowalski", ln=True)
    pdf.field_label("Geburtsdatum:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "15.03.2018", ln=True)
    pdf.field_label("Geburtsort:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Warszawa, Polska", ln=True)
    pdf.field_label("Sozialversicherungsnummer des Kindes (falls deutsche):")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "keine — Kind in Polen gemeldet", ln=True)
    pdf.field_label("Lebt das Kind beim Antragsteller?")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Ja — ständiger Wohnsitz beim Elternteil in Polen", ln=True)

    pdf.add_page()
    pdf.section_title("Formular KG 3 — Angaben zum zweiten Elternteil")
    pdf.body_text("Ausfüllen, wenn der zweite Elternteil lebt und nicht mit dem Antragsteller zusammenlebt.")
    pdf.field_label("Vor- und Nachname des zweiten Elternteils:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Jan Kowalski", ln=True)
    pdf.field_label("Meldeadresse des zweiten Elternteils:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "ul. Leśna 12, 00-001 Warszawa, Polska (gemeinsame Meldung)", ln=True)
    pdf.field_label("Arbeitet der zweite Elternteil in Deutschland?")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Nein — arbeitet in Polen", ln=True)
    pdf.field_label("Bezieht der zweite Elternteil Kindergeld aus einer anderen Quelle?")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Nein", ln=True)

    pdf.section_title("Formular KG 4 — Erklärung zur Wohnsituation")
    pdf.body_text("Bestätigung, dass das Kind beim Antragsteller lebt.")
    pdf.field_label("Adresse, unter der das Kind tatsächlich wohnt:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "ul. Leśna 12, 00-001 Warszawa, Polska", ln=True)
    pdf.field_label("Datum des Beginns des Zusammenwohnens:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "seit der Geburt des Kindes — 15.03.2018", ln=True)

    pdf.section_title("Formular KG 5 — Einverständnis des zweiten Elternteils (falls erforderlich)")
    pdf.body_text("Wenn die Eltern getrennt leben oder der zweite Elternteil im Ausland arbeitet, ist eine Einverständniserklärung erforderlich, um das Kindergeld an den Antragsteller zu überweisen.")
    pdf.field_label("Unterschrift des zweiten Elternteils + Datum:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Jan Kowalski, 05.01.2025", ln=True)
    pdf.field_label("Ist die Einverständniserklärung notariell oder amtlich beglaubigt?")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Nicht erforderlich — Eltern gemeinsam gemeldet", ln=True)

    pdf.section_title("Formular KG 6 — Angaben zum Arbeitgeber und zur Sozialversicherung")
    pdf.field_label("Name des deutschen Arbeitgebers:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "Muster GmbH, Köln", ln=True)
    pdf.field_label("Sozialversicherungsnummer des Antragstellers:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "12 123456 A 123", ln=True)
    pdf.field_label("Beginn der Beschäftigung in Deutschland:")
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 6, "01.03.2022 — bis heute", ln=True)

    pdf.add_page()
    pdf.section_title("Häufigste Fehler beim Ausfüllen")
    pdf.body_text("1. Falsche Familienkasse-Adresse — prüfen Sie immer, welches Büro Ihrem Arbeitgeber zugeordnet ist.")
    pdf.body_text("2. Fehlende Steuer-ID — falls Sie keine haben, kreuzen Sie das entsprechende Feld an und legen Sie eine Kopie des Passes bei.")
    pdf.body_text("3. Unvollständige Kindesangaben — geben Sie das genaue Geburtsdatum und den Geburtsort aus der Geburtsurkunde an.")
    pdf.body_text("4. Fehlende Unterschrift des zweiten Elternteils — bei Trennung der Eltern ist die Einverständniserklärung Pflicht.")
    pdf.body_text("5. Veraltete Adresse — bei Umzug melden Sie die Adressänderung zuerst beim Einwohnermeldeamt.")
    pdf.body_text("6. Originalunterlagen senden — senden Sie immer Kopien, behalten Sie die Originale.")

    pdf.section_title("Erforderliche Anlagen (Kopien)")
    pdf.body_text("□ Geburtsurkunde des Kindes (mit beglaubigter Übersetzung ins Deutsche)")
    pdf.body_text("□ Pass oder Personalausweis des Antragstellers")
    pdf.body_text("□ Lohnabrechnung / Lohnsteuerbescheinigung (Nachweis der Beschäftigung in Deutschland)")
    pdf.body_text("□ Meldebestätigung des Kindes in Polen (vom Bürgeramt)")
    pdf.body_text("□ Einverständniserklärung des zweiten Elternteils (falls erforderlich)")

    pdf.info_box("E-mail:  Haben Sie Zweifel? Senden Sie Ihre ausgefüllten Formulare an igawo14@gmail.com oder rufen Sie an +48 570 016 826. Wir prüfen, ob alles korrekt ausgefüllt ist, bevor Sie den Antrag an die Familienkasse senden.")

    pdf.output(f"{OUTPUT_DIR}/kindergeld-antrag-vorlage.pdf")
    print("Generated: kindergeld-antrag-vorlage.pdf")


if __name__ == "__main__":
    make_german_questionnaire_pl()
    make_german_questionnaire_en()
    make_german_questionnaire_de()
    make_dutch_questionnaire_pl()
    make_dutch_questionnaire_en()
    make_dutch_questionnaire_de()
    make_kindergeld_template_pl()
    make_kindergeld_template_en()
    make_kindergeld_template_de()
    print("\n✅ All 9 PDFs generated successfully in public/downloads/")
